WebApplication1/Models/ManageViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace WebApplication1.Models
{
    public class IndexViewModel
    {
        [Display(Name = "Адрес электронной почты")]
        public string Email { get; set; }

        [Required]
        [StringLength(256, ErrorMessage = "Значение {0} должно содержать не менее {2} символов.", MinimumLength = 2)]
        [Display(Name = "Имя")]
        public string FirstName { get; set; }

        [Required]
        [StringLength(256, ErrorMessage = "Значение {0} должно содержать не менее {2} символов.", MinimumLength = 2)]
        [Display(Name = "Фамилия")]
        public string LastName { get; set; }

        public bool HasPassword { get; set; }
        public IList<UserLoginInfo> Logins { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFactor { get; set; }
        public bool BrowserRemembered { get; set; }
    }

    public class ManageLoginsViewModel
    {
        public IList<UserLoginInfo> CurrentLogins { get; set; }
        public IList<AuthenticationDescription> OtherLogins { get; set; }
    }

    public class FactorViewModel
    {
        public string Purpose { get; set; }
    }

    public class SetPasswordViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "Значение {0} должно содержать символов не менее: {2}.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Новый пароль")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Подтверждение нового пароля")]
        [Compare("NewPassword", ErrorMessage = "Новый пароль и его подтверждение не совпадают.")]
        public string ConfirmPassword { get; set; }
    }

    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Текущий пароль")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "Значение {0} должно содержать символов не менее: {2}.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Новый пароль")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Подтверждение нового пароля")]
        [Compare("NewPassword", ErrorMessage = "Новый пароль и его подтверждение не совпадают.")]
        public string ConfirmPassword { get; set; }
    }

    public class AddPhoneNumberViewModel
    {
        [Required]
        [Phone]
        [Display(Name = "Номер телефона")]
        public string Number { get; set; }
    }

    public class VerifyPhoneNumberViewModel
    {
        [Required]
        [Display(Name = "Код")]
        public string Code { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Номер телефона")]
        public string PhoneNumber { get; set; }
    }

    public class ConfigureTwoFactorViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
    }
}

WebApplication1/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Classes;
using WebApplication1.Models.ViewModels;

namespace WebApplication1.Controllers
{
    public class BlogController : Controller
    {
        const int postsOnPage = 10;
        // GET: Blog
        public ActionResult Index(int page = 1)
        {
            /*
            var posts = DataService.GetPostList(page, postsOnPage, true );

            var totalPosts = DataService.GetPostCount(true);

            var postList = new BlogPostListViewModel()
            {
                Posts = posts,
                TotalPosts = totalPosts
            };
            */
            var postList = new BlogPostListViewModel(page: page, postsOnPage: postsOnPage, onlyPublished: true);
            return View(postList);
        }
        public ActionResult Category(string category, int page = 1, bool onlyPublished = true)
        {
            // TODO: get the posts for the category and return the view.
            var Category = DataService.GetBlogCategory(category);

            if (String.IsNullOrEmpty(Category.CategoryId))
                throw new HttpException(404, "Категория не существует");

            /*
            var posts = DataService.GetPostList(page, postsOnPage, onlyPublished, category);
            var totalPosts = DataService.GetPostCount(onlyPublished, category);

            var postList = new BlogPostListViewModel()
            {
                Posts = posts,
                TotalPosts = totalPosts,
                Category = Category
            };
            */
            var postList = new BlogPostListViewModel(page, postsOnPage, onlyPublished, Category);
            ViewBag.Title = String.Format(@"Статьи в рубрике: ""{0}""",
                                    Category.Name);
            return View("Index", postList);
        }

        public ActionResult Tag(string tag, int page = 1, bool onlyPublished = true)
        {
            // TODO: get the posts for the category and return the view.
            var Tag = DataService.GetBlogTag(tag);

            if (String.IsNullOrEmpty(Tag.TagId))
                throw new HttpException(404, "Тег не существует");

            /*
            var posts = DataService.GetPostListByTag(page, postsOnPage, Tag.TagId, onlyPublished);
            var totalPosts = DataService.GetPostCount(onlyPublished, Tag.TagId);

            var postList = new BlogPostListViewModel()
            {
                Posts = posts,
                TotalPosts = totalPosts,
                Tag = Tag
            };
            */
            var postList = new BlogPostListViewModel(page, postsOnPage, onlyPublished, Tag);

            ViewBag.Title = string.Format(@"Все статьи с меткой ""{0}""",
                                    Tag.Name);
            return View("Index", postList);
        }

        public ActionResult Post(int year, int month, string title)
        {
            var post = DataService.GetPost(year, month, title);

            if (post == null)
                throw new HttpException(404, "Пост не найден");

            //TODO прямо в коде надо проверять на принадлежность к роли

            if (post.Published == false)
                throw new HttpException(404, "Пост не найден");

            return View(post);
        }


        [Authorize, Authorize(Roles = "Admin")]
        public ActionResult Manage(int page = 1)
        {
            //сделать аналог index с пагинацией
            /*
            var posts = DataService.GetPostList(page, postsOnPage, false);

            var totalPosts = DataService.GetPostCount(false);

            var postList = new BlogPostListViewModel()
            {
                Posts = posts,
                TotalPosts = totalPosts
            };
            */
            var postList = new BlogPostListViewModel(page: page, postsOnPage: postsOnPage, onlyPublished: false);

            return View(postList);
        }

        [Authorize, Authorize(Roles = "Admin")]
        public ActionResult AddPost()
        {
            BlogPostViewModel post = new BlogPostViewModel();
            return View("AddPost",post);
        }

        [HttpPost]
        [Authorize, Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult AddPost(BlogPostViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(model.UrlSlug) || string.IsNullOrWhiteSpace(model.UrlSlug))
                    model.UrlSlug = DataService.Transliteration.Front(model.Title.ToLower()).Replace(" ","-");

                if (string.IsNullOrEmpty(model.Meta) || string.IsNullOrWhiteSpace(model.Meta))
                    model.Meta = model.Title;

                var id = DataService.AddPost(model);
            }
            else
            {
                model.ErrorMessage = "Проверьте заполнение полей";
                return View("AddPost", model);
            }
            return RedirectToAction("Index");
        }

        [Authorize, Authorize(Roles = "Admin")]
        public ActionResult EditPost(string id)
        {
            BlogPostViewModel post = DataService.GetPostById(id);
            if (post.PostId == "")
                throw new HttpException(404, "Пост не найден");
            return View("EditPost", post);
        }

        [HttpPost]
        [Authorize, Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult EditPost(BlogPostViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.ErrorMessage = string.Empty;
                if (string.IsNullOrEmpty(model.Meta) || string.IsNullOrWhiteSpace(model.Meta))
                    model.Meta = model.Title;

                var answer = DataService.EditPost(model);
                if (answer!= "OK")
                {
                    model.ErrorMessage = answer; 
                    return View("EditPost", model);
                }
            }
            else
            {
                model.ErrorMessage = "Проверьте заполнение полей";
                return View("AddPost", model);
            }
            return RedirectToAction("Index");
        }

        public string Upload(HttpPostedFileBase file)
        {
            string path = String.Empty;
            string saveloc = "/img/";
            string relativeloc = "/img/";
            string filename = Path.GetFileName(file.FileName);

            //var ret = "<script>top.$('.mce-btn.mce-open').parent().find('.mce-textbox').val('" + "http://bulanov/krasivo.local/img/me.png" + "').closest('.mce-window').find('.mce-primary').click();</script>";
            //return ret;

            if (file != null && file.ContentLength > 0) //TODO: проверка на то, что файл - реально картинка
            {
                try
                {
                    var curDate = DateTime.Today;
                    var curYear = curDate.Year;
                    var curMonth = curDate.Month;


                    var path2save = Path.Combine(HttpContext.Server.MapPath(saveloc), curYear.ToString() + "\\" + curMonth.ToString() + "\\");
                    var ext = Path.GetExtension(filename);
                    var nameWOExt = Path.GetFileNameWithoutExtension(filename);

                    if (!Directory.Exists(path2save))
                        Directory.CreateDirectory(path2save);

                    path = path2save;
                    relativeloc = Path.Combine(relativeloc, curYear.ToString() + "//" + curMonth.ToString() + "//");
                    path2save = Path.Combine(path2save, filename);
                    var i = 1;
                    while (System.IO.File.Exists(path2save))
                    {
                        var fName = nameWOExt + "-" + i.ToString() +  ext;
                        path2save = Path.Combine(path, fName);
                        i++;
                    }

                    file.SaveAs(path2save);
                }
                catch (Exception e)
                {
                    return "<script>alert('Failed: " + e + "');</script>";
                }
            }
            else
            {
                return "<script>alert('Failed: Unkown Error. This form only accepts valid images.');</script>";
            }
            //т.е. здесь мы закачали
            //теперь нужен метод контроллера, который нам вернёт
            return "<script>top.$('.mce-btn.mce-open').parent().find('.mce-textbox').val('" + relativeloc + filename + "').closest('.mce-window').find('.mce-primary').click();</script>";
        }
    }
}

WebApplication1/Views/Blog/AddPost.cshtml
@model WebApplication1.Models.ViewModels.BlogPostViewModel

@{
    ViewBag.Title = "Новая статья";
}
<h2>Новая статья</h2>
@using (Html.BeginForm("AddPost", "Blog", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    //вот здесь место для партиала
    @Html.Partial("PostEditorPartial", Model)
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Сохранить" class="btn btn-default" />
        </div>
    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<iframe id="form_target" name="form_target" style="display:none"></iframe>
@using (Html.BeginForm("Upload", "Blog", FormMethod.Post, htmlAttributes: new { @target = "form_target", @enctype = "multipart/form-data", @id = "my_form", @style = "width:0;height:0;overflow:hidden" }))
{
    <input name="file" type="file" onchange="$('#my_form').submit();this.value='';">
}

WebApplication1/Views/Blog/EditPost.cshtml
@model WebApplication1.Models.ViewModels.BlogPostViewModel

@{
    ViewBag.Title = "Редактор статей";
}
<h2>Редактировать статью</h2>
@using (Html.BeginForm("EditPost", "Blog", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    //вот здесь место для партиала
    @Html.Partial("PostEditorPartial", Model)
    <iframe id="form_target" name="form_target" style="display:none"></iframe>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Сохранить" class="btn btn-default" />
        </div>
    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@using (Html.BeginForm("Upload", "Blog", FormMethod.Post, htmlAttributes: new { @target = "form_target", @enctype = "multipart/form-data", @id = "my_form", @style = "width:0;height:0;overflow:hidden" }))
    {
    <input name="file" type="file" onchange="$('#my_form').submit();this.value='';">
    }

WebApplication1/Views/Blog/Editor.cshtml
@model WebApplication1.Models.ViewModels.BlogPostViewModel

@{
    ViewBag.Title = "Редактор статей";
}

<h2>Новая статья</h2>
<script src="~/Scripts/tinymce/tinymce.min.js"></script>
<!-- Script to wire up your TinyMCE editor -->
<script type="text/javascript">
        // Initialize your tinyMCE Editor with your preferred options
        tinyMCE.init({
            // General options
            mode: "textareas",
            theme: "modern",
            // Theme options
            theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
            theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|, search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
            theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
            theme_advanced_toolbar_location: "top",
            theme_advanced_toolbar_align: "left",
            theme_advanced_statusbar_location: "bottom",
            theme_advanced_resizing: true,

            // Example content CSS (should be your site CSS)
            content_css: "css/example.css",
        });
</script>
@using (Html.BeginForm("AddPost", "Blog", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
            @Html.HiddenFor(model => model.PostId)
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Meta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Meta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Meta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UrlSlug, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if(String.IsNullOrEmpty(Model.PostId))
                { 
                    @Html.EditorFor(model => model.UrlSlug, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UrlSlug, "", new { @class = "text-danger" })
                }
                else
                {
                    @Html.DisplayFor(model => model.UrlSlug, new { htmlAttributes = new { @class = "form-control" } })
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TagString, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TagString, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TagString, "", new { @class = "text-danger" })
            </div>
        </div>


        @Html.DropDownListFor(m => m.Category.CategoryId, new SelectList(Model.Category.Items, "CategoryId", "Name"))

        <div class="form-group">
            @Html.LabelFor(model => model.Published, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Published)
                    @Html.ValidationMessageFor(model => model.Published, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication1/Views/Blog/Index.cshtml
@model  WebApplication1.Models.ViewModels.BlogPostListViewModel
<h2>Index</h2>

<div id="content">

    <h1>@ViewBag.Title</h1>

    @if (Model.Posts.Count > 0)
    {
        foreach (var post in Model.Posts)
        {
            @Html.Partial("PostTemplate", post)
        }
    }
    else
    {
        <p>Статьи не найдены</p>
    }

@Html.Partial("Pager", Model)

</div>

WebApplication1/Views/Blog/Manage.cshtml
@model  WebApplication1.Models.ViewModels.BlogPostListViewModel
<h2>Консоль администратора</h2>

<div id="content">

    @if (Model.Posts.Count > 0)
    {
         <table>
             <tr>
                 <th>
                    @Html.Label("Порядковый номер");
                 </th>
                 <th>
                     @Html.Label("Код");
                 </th>
                 <th>
                     @Html.Label("Заголовок");
                 </th>
                 <th>
                     @Html.Label("Опубликовано");
                 </th>
                 <th>
                     @Html.Label("Метки");
                 </th>
                 <th>
                     @Html.Label("Категория");
                 </th>
                 <th>
                     @Html.Label("Дата публикации");
                 </th>
                 <th>
                     @Html.Label("Дата последнего редактирования");
                 </th>
             </tr>
            @foreach (var post in Model.Posts)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => post.OrderNumber)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => post.PostId)
                    </td>
                    <td>
                        @Html.ActionLink(Html.DisplayFor(modelItem => post.Title).ToString(), "EditPost", new { Id = post.PostId })
                        @*@Html.DisplayFor(modelItem => post.Title)*@
                    </td>
                    <td>
                        @if (post.Published)
                        {
                            @Html.Label("Опубликован");
                        }
                        else
                        {
                            @Html.Label("Не опубликован");
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => post.TagString)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => post.Category.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => post.PostedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => post.Modified)
                    </td>

                </tr>
            }
        </table>
    }
    else
    {
        <p>Статьи не найдены</p>
    }

    @Html.Partial("Pager", Model)

</div>

WebApplication1/Views/Blog/Post.cshtml
@model WebApplication1.Models.ViewModels.BlogPostViewModel

@{
    ViewBag.Title = Model.Title;
    ViewBag.Keywords = string.Join(" ", Model.Tags.Select(t => t.Name).ToArray());
    ViewBag.Description = Model.Meta;
}

<div id="content">
    <div class="post">
        <div class="post-meta">
            <div class="row">

                <div class="post-title">
                    <h1>@Html.PostLink(Model)</h1>
                </div>

            </div>
            <div class="row">

                <div class="post-category">
                    <span>Category:</span> @Html.CategoryLink(Model.Category)
                </div>

                <div class="post-tags">
                    <span>Tags:</span> @Helpers.Tags(Html, Model.Tags)
                </div>

                <div class="posted-date">
                    @Model.PostedOn
                </div>

            </div>
        </div>

        <div class="post-body">
            @Html.Raw(Model.Description)
        </div>

    </div>
</div>