WebApplication1/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Classes;
using WebApplication1.Models.ViewModels;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;

namespace WebApplication1.Controllers
{
    public class BrandController : Controller
    {
        private ApplicationUserManager _userManager;
        public BrandController()
        {

        }

        public BrandController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        // GET: Brand
        public ActionResult Index()
        {
            var model = new List<BrandViewModel>();
            try
            {
                var strUrl = "//krasivo.pro/";// DataService.GetUrl(Request);
                model = DataService.GetBrandsCatalog(strUrl);
                ViewBag.Title = "Бренды в интернет-магазине Индустрия Красоты";
                ViewBag.Keywords = "Интернет-магазин Индустрия красоты, Krasivo.pro, красиво.про, красиво про, профессиональная косметика известных брендов. Купить Elgon, купить elgon в Ростове-на-Дону, купить Tigi, купить tigi в Ростове-на-Дону, купить Moser, купить Moser в Ростове-на-Дону, купить selective, купить selective в ростове-на-дону, купить Barex, купить Barex в Ростове-на-Дону, barex, elgon, selective, inebrya, elgon, moser, parlux, dewal, интернет-магазин";
                ViewBag.Description = "Интернет-магазин Индустрия красоты. Профессиональная косметика Elgon, Tigi, Aravia, Wella, Inebrya, Selective, Barex, техника Parlux, Dewal, Tayo, Babyliss и многое другое!";
            }
            catch
            {
                model = new List<BrandViewModel>();
            }
            return View(model);
        }

        public ActionResult Details(string Id)
        {
            //id здесь slug на самом деле, чтобы было красивенько
            var model = new BrandViewModel();

            try
            {
                string userId;
                if (Request.IsAuthenticated)
                    userId = User.Identity.GetUserId();
                else
                    userId = Request.AnonymousID;

                var strUrl = "//krasivo.pro/"; //DataService.GetUrl(Request);
                model = DataService.GetBrandInfoBySlug(Id, strUrl);
                //
                if (!string.IsNullOrWhiteSpace(model.FilterString))
                { 
                    var parsedFilterString = new List<QualityGoodItem>();
                    var SortNum2Start = 0;
                    var forceSelectedItems = true;
                    var selectedItems = new List<string>();
                    var actionId = string.Empty;
                    var orderId = string.Empty;

                    if (!String.IsNullOrEmpty(model.FilterString))
                    {
                        parsedFilterString = DataService.ParseFilterString(model.FilterString, out SortNum2Start, out actionId, out orderId);
                        selectedItems = DataService.GetItemsList(parsedFilterString);
                    }

                    //filterList = DataService.GetFilterList(parsedFilterString); //вот сюда помеченные надо добавлять

                    model.FeaturedItems= DataService.GetCatalogByItemList(selectedItems, forceSelectedItems, strUrl, 20, true, userId, 0, true);
                }

                ViewBag.Title = model.BrandName;
                ViewBag.Description = DataService.StripHTML(model.BrandDescription);
                ViewBag.Keywords = model.BrandName;

            }
            catch
            {
                RedirectToAction("Index");
            }            
            return View(model);
        }
    }
}

WebApplication1/Views/Shared/BannerPartial.cshtml
@model List<WebApplication1.Models.ViewModels.BannerViewModel>
@if (Model.Any())
{
    <div class="special_block">
        <div class="special_list special_slider">
            @foreach (var banner in Model)
            {
                <a href="@banner.LinkTo" Id = @banner.Id class="item big_product">
                    <img src="@banner.PathToImage" alt="@banner.Description" />
                </a>
            }
            @*<a href="@Url.Action("Details","SaleAction", new { Id = Model[0].UrlSlug })" class="item big_product">
                    <img src="@Model[0].LongMainImage" alt="@Model[0].Title" />
                </a>*@
            @*<a href="@Url.Action("Details","SaleAction", new { Id = Model[0].UrlSlug })" class="item big_product">
                    <img src="@Model[0].LongMainImage" alt="@Model[0].Title" />
                </a>*@
        </div>
    </div>
}

WebApplication1/Views/Shared/BrandPartial.cshtml
@model IEnumerable<WebApplication1.Models.ViewModels.BrandViewModel>
@{ if (Model.Any())
    {
        @*<div class="brands_list">*@
            foreach (var brand in Model)
            {
                <a href="@Url.Action("Details","Brand",new { Id = brand.UrlSlug })" class="item"><img src="@brand.MainImagePath[1]" alt="@brand.BrandName" /></a>
            }
        @*</div>*@
    }
    else
    {
        @Html.Raw("<p>Раздел в разработке</p>")
    }
}

WebApplication1/Views/Shared/CustomError.cshtml
@model WebApplication1.Models.CustomErrorModel

@{
    ViewBag.Title = "Ошибка";
}

<h2>@Model.ErrorTitle</h2>
<h3>@Model.ErrorDescription </h3 >

WebApplication1/Views/Shared/CustomLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CustomLayout</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

WebApplication1/Views/Shared/FilterPartial.cshtml
@model IEnumerable<WebApplication1.Models.FilterTreeModel>

<aside class="filter_block">
    <div class="title">Фильтры</div>
    <div class="filter_list">
        @foreach (var item in Model)
        {
            <ul class="item">
                <li class="item_group">
                    <span class="head_filter @{if (!item.Enabled)
                                    {<text>dis</text>}}" id="@item.Id">@Html.DisplayFor(model => item.Name)</span>
                                    <ul class="value_list">
                                        @foreach (var subitem in item.TreeNodeModel)
                                        {
                                            <li class="value_item @{if (subitem.Checked) { <text>check</text>} } @{if (!subitem.Enabled) {<text>dis</text>}}">
                                                <label>
                                                    <input type="checkbox" class="prop_value"
                                                           name="@item.Id" value="@subitem.Id"
                                                           @{if (subitem.Checked) { <text> checked='checked' </text>      } }
                                                           />
                                                    @subitem.Title
                                                </label>
                                            </li>
    }
                                    </ul>
                                </li>
                            </ul>
    }
    </div>
    <div class="btns">
        <a href="#" class="do_filt">показать</a>
        <a href="#" class="clear_filt">очистить фильтр</a>
    </div>

    <div class="tmpFilter" data-filter-url='/InventTable/GetFilteredItemsQty' data-products-url='/InventTable/GetItemsPartial' data-filter-items='/InventTable/GetNewFilter' data-index-url='/catalog'></div>
    @*<div class="tmpFilter" data-filter-url='https://krasivo.pro/591684AE-4993-4864-BBB9-49F94231E48A/InventTable/GetFilteredItemsQty' data-products-url='https://krasivo.pro/591684AE-4993-4864-BBB9-49F94231E48A/InventTable/GetItemsPartial' data-filter-items='https://krasivo.pro/591684AE-4993-4864-BBB9-49F94231E48A/InventTable/GetNewFilter' data-index-url='https://krasivo.pro/591684AE-4993-4864-BBB9-49F94231E48A/catalog'></div>*@
    <div class="count_block">
        <div class="count_text">Выбрано: <span class="count_value"></span></div>
        <a href="#" class="do_filt">показать</a>
    </div>
    <div class="mgz_link">        
        <a href="@Url.Action("Index","Magazine")" target="_blank" title="Гид по профессиональной косметике"><img src="https://krasivo.pro/pic/journal/2017/cover-03.png" alt=""></a>
    </div>

</aside>

WebApplication1/Views/Shared/FilterPartial4Action.cshtml
@model WebApplication1.Models.ViewModels.PublicityActionViewModel
@{ 
    var orderId = @Model.OrderId;
    var actionId = @Model.JournalId;
    var dataIndex = "/Basket/GivePresentsByAction?orderId=" + @orderId + "&actionId=" + @actionId;
    var dataFilterUrl = "/Basket/GetFilteredItemsQty?orderId=" + @orderId + "&actionId=" + @actionId;
    var dataProductsUrl = "/Basket/GetItemsPartial?orderId=" + @orderId + "&actionId=" + @actionId;
    var dataFilterItems = "/Basket/GetNewFilter?orderId=" + @orderId + "&actionId=" + @actionId;

//<aside class="filter_block">
    <div class="title">Фильтры</div>
    <div class="filter_list">
        @foreach (var item in Model.Filter)
        {
            <ul class="item">
                <li class="item_group">
                    <span class="head_filter @{if (!item.Enabled)
                                    {<text>dis</text>}}" id="@item.Id">@Html.DisplayFor(model => item.Name)</span>
                                    <ul class="value_list">
                                        @foreach (var subitem in item.TreeNodeModel)
                                        {
                                            <li class="value_item @{if (subitem.Checked) { <text>check</text>} } @{if (!subitem.Enabled) {<text>dis + </text>}}">
                                                <label>
                                                    <input type="checkbox" class="prop_value"
                                                           name="@item.Id" value="@subitem.Id"
                                                           @{if (subitem.Checked) { <text> checked='checked' </text>      } }
                                                           />
                                                    @subitem.Title
                                                </label>
                                            </li>
                                        }
                                    </ul>
                                </li>
                            </ul>
    }
    </div>
    <div class="btns">
        <a href="#" class="do_filt">показать</a>
        <a href="#" class="clear_filt">очистить фильтр</a>
    </div>
    
    <div class="tmpFilter" data-filter-url='@dataFilterUrl' data-products-url='@dataProductsUrl' data-filter-items='@dataFilterItems' data-index-url='@dataIndex'></div>
    @*<div class="tmpFilter" data-filter-url='https://krasivo.pro/591684AE-4993-4864-BBB9-49F94231E48A/InventTable/GetFilteredItemsQty' data-products-url='https://krasivo.pro/591684AE-4993-4864-BBB9-49F94231E48A/InventTable/GetItemsPartial' data-filter-items='https://krasivo.pro/591684AE-4993-4864-BBB9-49F94231E48A/InventTable/GetNewFilter' data-index-url='https://krasivo.pro/591684AE-4993-4864-BBB9-49F94231E48A/catalog'></div>*@
    <div class="count_block">
        <div class="count_text">Выбрано: <span class="count_value"></span></div>
        <a href="#" class="do_filt">показать</a>
    </div>
@*</aside>*@
}

WebApplication1/Views/Shared/ItemsPartial4Action.cshtml
@model WebApplication1.Models.ViewModels.PublicityActionViewModel

@{ if (Model.PublicityItems.Any())
    {
            foreach (var item in Model.PublicityItems)
            {
                if (item.AvailQty == 0)
                {
                    continue;
                }

                <div class="item product_item @{if (item.Hit) { <text>hit</text>} } @{if (item.isAction) { <text>action</text>} } ">
                    <div class="photo"><img src=@item.MainImagePath[1] alt="@item.ItemName" /></div>
                    <div class="title">@Html.DisplayFor(model => item.ItemName)</div>

                    <input type="hidden" class="item_num" value="@item.OrderNumber" />

                    <div class="price_block">

                        <span class="price">Цена в баллах: @Html.DisplayFor(modelItem => item.PointsCost)&nbsp;<i class="fa" aria-hidden="true"></i></span>

                    </div>
                    @if (item.PointsCost <= @Model.PointsEarned)
                    {
                        <div class="quantity_block_p" data-max-value=@item.AvailQty data-price="@Html.DisplayFor(modelItem => item.PointsCost)">
                            <label class="control-label">Выбрано:</label>
                            <span class="counter counter-minus @{if (item.QtyGiven == 0) { <text>dis</text> } }" data-id="@item.ItemId" data-order-id="@Model.OrderId" data-action-id="@Model.JournalId">
                                <i class="fa fa-minus" aria-hidden="true"></i>
                            </span>
                            <span class="quantity" name="quantity">@Html.DisplayFor(model => item.QtyGiven)</span>

                            <span class="counter counter-plus @{if (item.PointsCost > (@Model.PointsEarned - @Model.PointsGiven)) { <text>dis</text> } } " data-id="@item.ItemId" data-order-id="@Model.OrderId" data-action-id="@Model.JournalId">
                                <i class="fa fa-plus" aria-hidden="true"></i>
                            </span>

                            <div class="cl"></div>
                        </div>
                    }
                    else
                    {
                        <span class="comment">
                            Недостаточно баллов для этого подарка
                        </span>
                    }
                </div>
    }

        <div class="more_block">
            <div class="cl"></div>
            <a class="show_more" href="#">показать еще</a>
        </div>

    }
    else
    {
        <div class="cl"></div>
        @Html.Raw("<p class='no_result'>Извините, по вашему запросу товары отсутствуют.</p>");
    }
}

WebApplication1/Views/Shared/OrderDeliveryParamsPartial.cshtml
@using WebApplication1.Models.ViewModels
@using WebApplication1.Classes
@model WebApplication1.Models.ViewModels.OrderViewModel
@if (@Model!=null)
{
@*сначала вытащим параметры доставки*@
var deliveryTypeItem = Model.DeliveryType.TypeItems.FirstOrDefault(x => x.DeliveryTypeId == Model.DeliveryType.SelectedDeliveryTypeId);
var deliveryModeItem = new DeliveryModeRadioItem();
var cityName = string.Empty;
var deliveryModeId = string.Empty;
var deliveryModeName = string.Empty;
var selfDeliveryPointName = string.Empty;
var selfDeliveryPointDesc = string.Empty;
var deliveryAddressStreet = string.Empty;
var deliveryAddressBuilding = string.Empty;
var deliveryAddressAppt = string.Empty;
var deliveryAddressGate = string.Empty;
var deliveryAddressLevel = string.Empty;
var deliveryAddressIntercom = string.Empty;
var transportLeg = Model.TransportLeg;
var deliveryCost = Model.DeliveryCost;
var deliveryTypeId = Model.DeliveryType.SelectedDeliveryTypeId;
var trackingNumber = Model.TrackingNumber;

if (deliveryTypeItem!=null)
{
    cityName = deliveryTypeItem.SelectedCityName;    
    deliveryModeItem = deliveryTypeItem.ModeItems.FirstOrDefault(x => x.DeliveryModeId == deliveryTypeItem.SelectedDeliveryModeId);
    if (deliveryModeItem!=null)
    {        
        deliveryModeId = deliveryModeItem.DeliveryModeId;
        deliveryModeName = deliveryModeItem.Name;
        selfDeliveryPointName = deliveryModeItem.SelectedSelfDeliveryPointName;
        selfDeliveryPointDesc = deliveryModeItem.SelectedSelfDeliveryPointDescription;

        deliveryAddressStreet = deliveryModeItem.DeliveryAddressStreet;
        deliveryAddressBuilding = deliveryModeItem.DeliveryAddressBuilding;
        deliveryAddressAppt = deliveryModeItem.DeliveryAddressAppt;
        deliveryAddressGate = deliveryModeItem.DeliveryAddressGate;
        deliveryAddressLevel = deliveryModeItem.DeliveryAddressLevel;
        deliveryAddressIntercom = deliveryModeItem.DeliveryAddressIntercomCode;
    }
}
    @*Вытащили параметры*@
    <span>Способ доставки: @deliveryModeName</span><br />
    if (deliveryCost>0)
    { 
        <span>Стоимость доставки: @deliveryCost <i class="fa fa-rub" aria-hidden="true"></i></span><br />
    }
    else
    {
        <span>Стоимость доставки: Бесплатно <i class="fa fa-rub" aria-hidden="true"></i></span><br />
    }
    if (Model.PaymentType.SelectedPaymentTypeId == PaymentTypeStatic.CardPaymentTypeId)
    { 
        if (deliveryModeId == DeliveryTypeStatic.SelfDeliveryModeId)
        {
            <span>Срок доставки после оплаты, рабочих дней: @transportLeg</span><br />
        }
        else
        {
            <span>Срок доставки после оплаты, рабочих дней: @transportLeg</span><br />
        }
    }
    else
    {
        if (deliveryModeId == DeliveryTypeStatic.SelfDeliveryModeId)
        {
            <span>Срок доставки, рабочих дней: @transportLeg</span><br />
        }
        else
        {
            <span>Срок доставки, рабочих дней: @transportLeg</span><br />
        }
    }
    <span>Город: @cityName</span><br />

    if (deliveryModeId == DeliveryTypeStatic.CDEKPVZ10ModeId || deliveryModeId == DeliveryTypeStatic.CDEKPVZ136ModeId || deliveryModeId == DeliveryTypeStatic.SelfDeliveryModeId)
    {
        <span>Пункт самовывоза: @selfDeliveryPointName</span><br />
        <span>@selfDeliveryPointDesc</span><br />
    }

    if (deliveryModeId == DeliveryTypeStatic.CDEKCourier11ModeId || deliveryModeId == DeliveryTypeStatic.CDEKCourier137ModeId)
    {
        if (!string.IsNullOrWhiteSpace(@deliveryAddressStreet))
        {
            <span>Улица: @deliveryAddressStreet</span><br />
        }

        if (!string.IsNullOrWhiteSpace(@deliveryAddressBuilding))
        {
            <span>Дом, строение, корпус: @deliveryAddressBuilding</span><br />
        }

        if (!string.IsNullOrWhiteSpace(@deliveryAddressAppt))
        {
            <span>Квартира, офис: @deliveryAddressAppt</span><br />
        }

        if (!string.IsNullOrWhiteSpace(@deliveryAddressGate))
        {
            <span>Подъезд: @deliveryAddressGate</span><br />
        }

        if (!string.IsNullOrWhiteSpace(@deliveryAddressLevel))
        {
            <span>Этаж: @deliveryAddressLevel</span><br />
        }

        if (!string.IsNullOrWhiteSpace(@deliveryAddressIntercom))
        {
            <span>Домофон: @deliveryAddressIntercom</span><br />
        }
        if (!string.IsNullOrWhiteSpace(@Model.Comment))
        {
            <span>Комментарий: @Model.Comment</span><br />
        }
    }
    if (!string.IsNullOrWhiteSpace(trackingNumber))
    {        
        <span>Номер накладной доставки: @trackingNumber</span><br />
        if (deliveryTypeId == DeliveryTypeStatic.CDEKDeliveryTypeId)
        {
            var cdekLink = "http://www.edostavka.ru/track.html?order_id=" + trackingNumber;
            <span>Отследить заказ на <a href = "@cdekLink" target="_blank" >сайте транспортной компании</a></span><br />
        }
    }
}

WebApplication1/Views/Shared/OrderSummaryPartial.cshtml
@model WebApplication1.Models.ViewModels.OrderSummaryViewModel

@if (Model.TotalAmount > 0)
{
    @Html.HiddenFor(model=>model.DeliveryTypeName)
    <div class="all_ammount line">
        <span class="title">@Html.DisplayNameFor(model=>model.TotalAmount)</span>
        <span class="value">@Html.DisplayFor(model => model.TotalAmount) <i class="fa fa-rub" aria-hidden="true"></i></span>
    </div>
}
<div class="order_ammount line">
    <span class="title">@Html.DisplayNameFor(model => model.ItemsQty) </span>
    <span class="value">@Html.DisplayFor(model => model.ItemsQty) </span>
</div>
<div class="order_ammount line">
    <span class="title">@Html.DisplayNameFor(model => model.OrderAmount)</span>
    <span class="value">@Html.DisplayFor(model => model.OrderAmount) <i class="fa fa-rub" aria-hidden="true"></i></span>
</div>

@if (Model.DeliveryCost > 0)
{
    <div class="delivery_ammount line">
        <span class="title">@Html.DisplayNameFor(model => model.DeliveryCost)</span>
        <span class="value">@Html.DisplayFor(model => model.DeliveryCost) <i class="fa fa-rub" aria-hidden="true"></i></span>
    </div>
}


@if (!string.IsNullOrEmpty(Model.DeliveryTypeName))
{
    <div class="delivery_type line">
        <span class="title">@Html.DisplayNameFor(model => model.DeliveryTypeName)</span>
        <span class="value">@Html.DisplayFor(model => model.DeliveryTypeName)</span>
    </div>
}

@if (!string.IsNullOrEmpty(Model.CityName))
{
    <div class="delivery_type line">
        <span class="title">@Html.DisplayNameFor(model => model.CityName)</span>
        <span class="value">@Html.DisplayFor(model => model.CityName)</span>
    </div>
}

@if (!string.IsNullOrEmpty(Model.DeliveryModeName))
{
    <div class="delivery_type line">
        <span class="title">@Html.DisplayNameFor(model => model.DeliveryModeName)</span>
        <span class="value">@Html.DisplayFor(model => model.DeliveryModeName)</span>
    </div>
}

@if (!string.IsNullOrEmpty(Model.PaymentTypeName))
{
    <div class="payment_type line">
        <span class="title">@Html.DisplayNameFor(model => model.PaymentTypeName)</span>
        <span class="value">@Html.DisplayFor(model => model.PaymentTypeName)</span>
    </div>
}

WebApplication1/Views/Shared/Pager.cshtml
@model WebApplication1.Models.ViewModels.BlogPostListViewModel

@* Read the current page and total pages *@

@{
    var currentPage = ViewContext.RequestContext.HttpContext.Request["page"] != null
      ? int.Parse(ViewContext.RequestContext.HttpContext.Request["page"])
      : 1;

    var totalPages = Math.Ceiling((double)Model.TotalPosts / 10);
}

@* Check do we need to display pagination links *@

@if (currentPage > 1 || currentPage < totalPages)
{
    var p = string.Format("page={0}", currentPage - 1);
    var n = string.Format("page={0}", currentPage + 1);

    @* If the view is rendered for "search" action append the pagination value with "&" *@

if (ViewContext.RouteData.Values["action"].ToString()
  .Equals("search", StringComparison.OrdinalIgnoreCase))
{
    var s = String.Format("?s={0}", ViewContext.RequestContext.HttpContext.Request.QueryString["s"]);
    p = String.Format("{0}&{1}", s, p);
    n = String.Format("{0}&{1}", s, n);
}
else
{
    p = String.Concat("?", p);
    n = String.Concat("?", n);
}

  <!--pagination links-->
    <div class="pager">

        <a href="@p" title="Previous" class="previous"
           style="visibility:@(currentPage > 1 ? "visible" : "collapse")"><< previous</a>

        <a href="@n" title="Next" class="next"
           style="visibility:@(currentPage < totalPages ? "visible" : "collapse")">next >></a>

    </div>
}

WebApplication1/Views/Shared/PostTemplate.cshtml
@model  WebApplication1.Models.ViewModels.BlogPostViewModel
@using WebApplication1.Classes

<div class="post">
    <div class="post-meta">
        <div class="row">

            <!--Heading-->
            <div class="post-title">
                <h2>@Html.PostLink(Model)</h2>
            </div>

        </div>

        <div class="row">

            <!--Category-->
            <div class="post-category">
                <span>Category: </span>@Html.CategoryLink(Model.Category)
            </div>

            <!--Tags-->
            <div class="post-tags">
                <span>Tags:</span>@Helpers.Tags(Html, Model.Tags)
            </div>

            <!--Posted date-->
            <div class="posted-date">
                @Model.PostedOn
            </div>

        </div>

    </div>

    <!--Short Description-->
    <div class="post-body">
        @Html.Raw(Model.ShortDescription)
    </div>

    <div class="post-foot">
        @Html.ActionLink("Далее...", "post", "blog",
        new
        {
            year = Model.PostedOn.Year,
            month = Model.PostedOn.Month,
            day = Model.PostedOn.Day,
            title = Model.UrlSlug
        },
        new { title = "Далее..." }
    )
    </div>
</div>

WebApplication1/Views/Shared/SaleActionsPartial.cshtml
@model List<WebApplication1.Models.ViewModels.SaleActionViewModel>
@if (Model.Any())
{ 
<div class="special_block">
    <div class="special_list special_slider">
        @foreach (var publicity in Model)
        {
            <a href="@Url.Action("Details","SaleAction", new { Id = @publicity.UrlSlug })" class="item big_product">
                <img src="@publicity.LongMainImage" alt="@publicity.Title" />
            </a>
        }
        @*<a href="@Url.Action("Details","SaleAction", new { Id = Model[0].UrlSlug })" class="item big_product">
            <img src="@Model[0].LongMainImage" alt="@Model[0].Title" />
        </a>*@
        @*<a href="@Url.Action("Details","SaleAction", new { Id = Model[0].UrlSlug })" class="item big_product">
            <img src="@Model[0].LongMainImage" alt="@Model[0].Title" />
        </a>*@ 
    </div>
</div>
}