WebApplication1/Controllers/CabinetController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization.Json;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Classes;
using WebApplication1.Models;
using WebApplication1.Models.ViewModels;

namespace WebApplication1.Controllers
{
    [Authorize]
    public class CabinetController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public CabinetController()
        {

        }

        public CabinetController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Cabinet
        [Authorize]
        public ActionResult Index(ManageMessageId? message)
        {
            ViewBag.StatusMessage =
                message == ManageMessageId.ChangePasswordSuccess ? "Ваш пароль изменен."
                : message == ManageMessageId.SetPasswordSuccess ? "Пароль задан."
                : message == ManageMessageId.SetTwoFactorSuccess ? "Настроен поставщик двухфакторной проверки подлинности."
                : message == ManageMessageId.Error ? "Произошла ошибка."
                : message == ManageMessageId.AddPhoneSuccess ? "Ваш номер телефона добавлен."
                : message == ManageMessageId.RemovePhoneSuccess ? "Ваш номер телефона удален."
                : "";

            var userId = User.Identity.GetUserId();
            var model = new PersonalInfoViewModel();

            ApplicationUser user = UserManager.FindByEmail(User.Identity.Name);

            if (!string.IsNullOrWhiteSpace(user.FirstName))
                model.FirstName = user.FirstName.ToString();
            else
                model.FirstName = string.Empty;
            if (!string.IsNullOrWhiteSpace(user.LastName))
                model.LastName = user.LastName.ToString();
            else
                model.LastName = string.Empty;
            if (!string.IsNullOrWhiteSpace(user.Email))
                model.Email = user.Email.ToString();
            else
                model.Email = string.Empty;
            if (!string.IsNullOrWhiteSpace(user.PhoneNumber))
                model.PhoneNumber = user.PhoneNumber.ToString();
            else
                model.PhoneNumber = string.Empty;

            model.AgreeToReceivePromoInfo = user.AgreeToReceivePromoInfo;

            ViewBag.Title = "Krasivo.pro - Личный кабинет";
            ViewBag.Description = "Интернет магазин Krasivo.pro. Профессиональная косметика известных брендов";
            ViewBag.Keywords = "Интернет магазин Krasivo.pro. Профессиональная косметика известных брендов";

            return View(model);
        }

        [Authorize]
        public ActionResult EditProfile()
        {
            var userId = User.Identity.GetUserId();
            var model = new PersonalInfoViewModel();

            ApplicationUser user = UserManager.FindByEmail(User.Identity.Name);

            if (!string.IsNullOrWhiteSpace(user.FirstName))
                model.FirstName = user.FirstName.ToString();
            else
                model.FirstName = string.Empty;
            if (!string.IsNullOrWhiteSpace(user.LastName))
                model.LastName = user.LastName.ToString();
            else
                model.LastName = string.Empty;
            if (!string.IsNullOrWhiteSpace(user.PhoneNumber))
                model.PhoneNumber = user.PhoneNumber.ToString();
            else
                model.PhoneNumber = string.Empty;

            model.AgreeToReceivePromoInfo = user.AgreeToReceivePromoInfo;

            ViewBag.Title = "Krasivo.pro - Редактирование личных данных";
            ViewBag.Description = "Интернет магазин Krasivo.pro. Профессиональная косметика известных брендов";
            ViewBag.Keywords = "Интернет магазин Krasivo.pro. Профессиональная косметика известных брендов";

            return View(model);
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult EditProfile(PersonalInfoViewModel PersonalInfoViewModel)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                var currentUser = UserManager.FindById(userId);


                currentUser.FirstName = PersonalInfoViewModel.FirstName;
                currentUser.LastName = PersonalInfoViewModel.LastName;

                currentUser.AgreeToReceivePromoInfo = PersonalInfoViewModel.AgreeToReceivePromoInfo;

                if (currentUser.PhoneNumber != PersonalInfoViewModel.PhoneNumber)
                {
                    currentUser.PhoneNumber = PersonalInfoViewModel.PhoneNumber;
                    currentUser.PhoneNumberConfirmed = false;
                }

                var ret = UserManager.Update(currentUser);

                /*
                model.FirstName = user.FirstName.ToString();
                model.LastName = user.LastName.ToString();
                model.Email = user.Email.ToString();
                model.PhoneNumber = user.PhoneNumber.ToString();
                */

                ViewBag.Title = "Krasivo.pro - Личный кабинет";
                ViewBag.Description = "Интернет магазин Krasivo.pro. Профессиональная косметика известных брендов";
                ViewBag.Keywords = "Интернет магазин Krasivo.pro. Профессиональная косметика известных брендов";

            }
            else
            {
                ViewBag.Title = "Krasivo.pro - Редактирование данных";
                ViewBag.Description = "Интернет магазин Krasivo.pro. Профессиональная косметика известных брендов";
                ViewBag.Keywords = "Интернет магазин Krasivo.pro. Профессиональная косметика известных брендов";

                return View(PersonalInfoViewModel);
            }
            return RedirectToAction("Index");
        }

        // GET: /Manage/ChangePassword

        public ActionResult ChangePassword()
        {
            ViewBag.Title = "Krasivo.pro - смена пароля";
            return View();
        }

        public ActionResult PayOrder(string id)
        {
            var saleInfo = new SaleInfo(id);

            if (saleInfo.OK)
            {

                var userId = User.Identity.GetUserId();

                if (saleInfo.PaymentTypeId == PaymentTypeId.Cash)
                {
                    var order = new OrderViewModel();
                    order.OrderId = id;
                    //TODO редирект на страницу, где говорится, что заказ ещё не может быть оплачен
                    return View("YouCantPayCODOnline");
                }

                /*
                if (userId != saleInfo.AspId)
                {
                    DataService.ReportAboutCrash("Кто-то попытался оплатить чужой заказ", userId + " " + saleInfo.AspId);
                    return RedirectToAction("Index","Home");
                }
                */

                switch (saleInfo.Status)
                {
                    //case SaleStatus.Picked:
                    case SaleStatus.Aside:
                        {
                            //всё хорошо, едем дальше
                            break;
                        }
                    case SaleStatus.Edit:
                        {
                            var order = new OrderViewModel();
                            order.OrderId = id;
                            //TODO редирект на страницу, где говорится, что заказ ещё не может быть оплачен
                            return View("PleaseWait");
                        }
                    default:
                        {
                            return View("PaymentError");
                            //throw new HttpException(string.Format("Кажется, что-то пошло не так"));
                        }
                }

                //var sberbankParams = DataService.GetSberbankParams();
                //ApplicationUser user = UserManager.FindByEmail(User.Identity.Name);
                ApplicationUser user = UserManager.FindById(saleInfo.AspId);
                var email = user.Email.ToString();

                if (saleInfo.PaymLinkExpDatetime == null || saleInfo.PaymLinkExpDatetime == DateTime.MinValue) //точно не оплачивали
                {
                    saleInfo.PaymServAlias = saleInfo.SalesId;
                    //вызываем регистрацию заказа на сервере
                    var answer = DataService.RegisterOrder(saleInfo, email);
                    //
                    if (answer.errorCode == null)
                        answer.errorCode = 0;
                    switch (answer.errorCode)
                    {
                        case 0:
                            {
                                var paymLinkExpDatetime = DateTime.Now.AddMinutes(19.98);
                                var paymServerOrderId = answer.orderId;
                                var paymServLink = answer.formUrl;
                                var paymServAlias = saleInfo.SalesId;

WebApplication1/Views/Cabinet/ChangePassword.cshtml
@model WebApplication1.Models.ChangePasswordViewModel
@{
    ViewBag.Title = "Смена пароля";
}
<div class="content_page syst">
    <h1>@ViewBag.Title</h1>

    @using (Html.BeginForm("ChangePassword", "Cabinet", FormMethod.Post, new { @class = "form-horizontal"}))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary("", new { @class = "text-danger" })
       
        <div class="fields">

            <label>
                <input class="field form-control" placeholder="Текущий пароль" data-val="true" data-val-required="Требуется поле Текущий пароль." id="OldPassword" name="OldPassword" type="password" />
            </label>
            <label>
                <input class="field form-control" placeholder="Новый пароль (мин. 6 символов)" data-val="true" data-val-length="Пароль должен содержать символов не менее: 6." data-val-length-max="100" data-val-length-min="6" data-val-required="Требуется поле Новый пароль." id="NewPassword" name="NewPassword" type="password" />
             </label>
            <label>
                <input class="field form-control" placeholder="Подтверждение пароля" data-val="true" data-val-equalto="Новый пароль и его подтверждение не совпадают." data-val-equalto-other="*.NewPassword" id="ConfirmPassword" name="ConfirmPassword" type="password" />
            </label>


            <input type="submit" class="btn btn-default" value="Изменить пароль" />
        </div>
    }
</div>

WebApplication1/Views/Cabinet/EditProfile.cshtml
@model WebApplication1.Models.ViewModels.PersonalInfoViewModel

<div class="content_page syst">
    <h1>Личный кабинет</h1>
    <p class="cab_menu">
        Профиль
        @Html.ActionLink("Мои заказы", "OrderList")
        @Html.ActionLink("Сменить пароль", "ChangePassword")
    </p>
    <h2>Редактирование личных данных</h2>

    @using (@Html.BeginForm("EditProfile", "Cabinet"))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary("", new { @class = "text-danger" })






        <div class="fields">

            <label>
                <input class="field text-box single-line" placeholder="Имя" data-val="true" data-val-length="Значение Имя должно содержать не менее 2 символов." data-val-length-max="256" data-val-length-min="2" data-val-required="Требуется поле Имя." id="FirstName" name="FirstName" value="@Model.FirstName" type="text" />
            </label>
            <label>
                <input class="field text-box single-line" placeholder="Фамилия" data-val="true" data-val-length="Значение Фамилия должно содержать не менее 2 символов." data-val-length-max="256" data-val-length-min="2" data-val-required="Требуется поле Фамилия." id="LastName" name="LastName" value="@Model.LastName" type="text" />
            </label>
            <label>
                <input class="m_phone field text-box single-line" placeholder="Номер телефона" data-val="true" data-val-phone="Поле Номер телефона не содержит допустимый номер телефона." data-val-required="Требуется поле Номер телефона." id="PhoneNumber" name="PhoneNumber" value="@Model.PhoneNumber" type="tel" />
            </label>
            <label>
                @Html.DisplayNameFor(model => model.AgreeToReceivePromoInfo):
                @Html.EditorFor(model => model.AgreeToReceivePromoInfo)                
            </label>
            <div class="btns">
                <input type="submit" class="in_row btn btn-default" value="Сохранить" />
                <a href="@Url.Action("Index","Cabinet")">Отмена</a>
            </div>
        </div>
    }
</div>

WebApplication1/Views/Cabinet/Index.cshtml
@model WebApplication1.Models.ViewModels.PersonalInfoViewModel

<div class="content_page syst">
    <h1>Личный кабинет</h1>
    <p class="cab_menu">
        @*@Html.ActionLink("Профиль", "Index", "Manage")*@
        Профиль
        @Html.ActionLink("Мои заказы", "OrderList")
        @Html.ActionLink("Сменить пароль", "ChangePassword")
    </p>
    <h3>Личные данные</h3>

    <p class="status_msg">@ViewBag.StatusMessage</p>

    <strong>@Html.DisplayNameFor(model => model.Email):</strong>
    @Html.DisplayFor(model => model.Email)
    <br />
    <strong>@Html.DisplayNameFor(model => model.FirstName):</strong>
    @Html.DisplayFor(model => model.FirstName)
    <br />
    <strong>@Html.DisplayNameFor(model => model.LastName):</strong>
    @Html.DisplayFor(model => model.LastName)
    <br />
    <strong>@Html.DisplayNameFor(model => model.PhoneNumber):</strong>
    @Html.DisplayFor(model => model.PhoneNumber)
    <br />
    <strong>@Html.DisplayNameFor(model => model.AgreeToReceivePromoInfo):</strong>
    @Html.DisplayFor(model => model.AgreeToReceivePromoInfo)
    <br />
    <a href="@Url.Action("EditProfile","Cabinet")" class="edit_profile">Редактировать</a>
</div>

WebApplication1/Views/Cabinet/OrderList.cshtml
@using WebApplication1.Classes
@model IEnumerable<WebApplication1.Models.ViewModels.OrderViewModel>
<div class="content_page syst order_list">
    <h1>Мои заказы</h1>

    @{if (@Model != null && Model.Any())
        {
            <div class="orders_list">

                @foreach (var item in Model)
                {
               
                <div class="orders_item">

                    <table>
                        <tr>
                            <td class="col1">
                                <span class="order_id">@Html.DisplayFor(modelItem => item.OrderId)</span><br/>
                                <span class="order_date">@item.SubmitDate.ToShortDateString()</span>
                            </td>
                            <td class="col2">
                                <a href="#" class="toggle_details">товаров: @Html.DisplayFor(modelItem => item.ItemsQty)</a>
                            </td>
                            <td class="col3">
                                <span class="item_status status1">@Html.DisplayFor(modelItem => item.StatusString)</span>
                            </td>
                            <td class="col4">
                                @if (item.DeliveryType!=null)
                                { 
                                    <span class="item_delivery_type">@Html.DisplayFor(modelItem => item.DeliveryType.SelectedDeliveryTypeDescription)</span>
                                }
                            </td>
                            <td class="col5">
                                <span class="item_ammount">@Html.DisplayFor(modelItem => item.TotalAmount) <i class="fa fa-rub" aria-hidden="true"></i></span>
                            </td>
                            <td class="col6">
                                @if (item.PaymentType != null)
                                {
                                    <span class="item_delivery_type">@Html.DisplayFor(modelItem => item.PaymentType.SelectedPaymentTypeName)</span>
                                }
                            </td>
                        </tr>
                    </table>
                    <div class="delivery_details">
                        @Html.Partial("OrderDeliveryParamsPartial", item)
                    </div>
                    <div class="item_details">
                        @Html.Partial("OrderItemsPartial", item.Items)
                    </div>

                    <div class="item_actions">

                        <div class="pay_status_list">
                            @if (item.PaymentType.SelectedPaymentTypeId == PaymentTypeStatic.CardPaymentTypeId)
                            { 
                                if (item.Status == WebApplication1.Classes.SaleStatus.Post || item.Status == WebApplication1.Classes.SaleStatus.Delivered || item.Status == WebApplication1.Classes.SaleStatus.SentToDelivery || item.Status == WebApplication1.Classes.SaleStatus.Received || item.Status == WebApplication1.Classes.SaleStatus.Storno)
                                {
                                    <span class="available"><i class="fa fa-check-circle" aria-hidden="true"></i> Оплачен</span><br />
                                }
                                else
                                {
                                    <span class="not_available"><i class="fa fa-ban" aria-hidden="true"></i> Не оплачен</span><br />
                                }
                            }
                        </div>

                        <div class="actions_list">
                            <a href="@Url.Action("RepeatOrder", "Cabinet", new { Id = item.OrderId })">Повторить заказ</a>

                            @if (item.Status == WebApplication1.Classes.SaleStatus.Aside)
                            {
                                <a href="@Url.Action("ReturnToBasket", "Cabinet", new { Id = item.OrderId })">Вернуть в корзину</a>
                            }
                            @if (item.PaymentType.SelectedPaymentTypeId == PaymentTypeStatic.CardPaymentTypeId)
                            { 
                                if (item.Status == WebApplication1.Classes.SaleStatus.Aside)
                                {
                                    <a href="@Url.Action("PayOrder", "Cabinet", new { Id = item.OrderId })">Оплатить заказ</a>
                                    <a href="@Url.Action("CheckOrderPayment", "Cabinet", new { Id = item.OrderId })">Проверить статус оплаты</a>
                                }
                            }
                            @if (item.Status != WebApplication1.Classes.SaleStatus.Cancel && item.Status != WebApplication1.Classes.SaleStatus.Storno && item.Status != WebApplication1.Classes.SaleStatus.Received && item.Status != WebApplication1.Classes.SaleStatus.Delivered)
                            {
                                <a href="@Url.Action("RejectOrder", "Cabinet", new { Id = item.OrderId })">Отменить заказ</a>
                            }
                        </div>

                    </div>

                    @Html.AntiForgeryToken()
                </div>



                }
            </div>
        }
        else
        {
            <div class="cart_empty_block active">
                <div class="cl"></div>
                <span class="icon">:-(</span>
                Вы ещё не сделали ни одного заказа.
            </div>
            }
        }

</div>

WebApplication1/Views/Cabinet/PaymentError.cshtml
<div class="content_page syst">
    <h1>Ошибка оплаты заказа</h1>
    <p>
        К сожалению, произошла ошибка оплаты заказа. Пожалуйста, свяжитесь со службой поддержки.
    </p>
</div>

WebApplication1/Views/Cabinet/PleaseWait.cshtml
<div class="content_page syst">
    <h1>Заказ пока не может быть оплачен</h1>
    <p>
        К сожалению, мы ещё не успели проверить ваш заказ, поэтому его пока нельзя оплатить. 
        Пожалуйста, дождитесь звонка от нашего менеджера. Приносим извинения за доставленные неудобства.
    </p>
    <p>Интернет-магазин "Индустрия Красоты"</p>
</div>

WebApplication1/Views/Cabinet/RejectOrder.cshtml
@using WebApplication1.Classes
@model WebApplication1.Models.ViewModels.OrderViewModel
@using (Html.BeginForm("RejectOrder", "Cabinet", FormMethod.Post))
{
    <div class="content_page syst">
        <h1>Отмена заказа @Model.OrderId</h1>
        @Html.HiddenFor(model => model.OrderId)
        @Html.AntiForgeryToken()
        @if(Model.PaymentType.SelectedPaymentTypeId == PaymentTypeStatic.CardPaymentTypeId)
        {
        <p>
            Если вы нажмёте сейчас кнопку "Отменить", ваш заказ будет отменён, а уплаченные деньги вернутся на вашу карту в течение 3 рабочих дней.
        </p>
        }
        else
        {
            <p>
                Если вы нажмёте сейчас кнопку "Отменить", ваш заказ будет отменён.
            </p>
        }
        <input type="submit" value="Отменить" />
        <p>
            @Html.ActionLink("Назад к списку заказов", "OrderList")
        </p>
    </div>
}

WebApplication1/Views/Cabinet/ReturnError.cshtml
<div class="content_page syst">
    <h1>Ошибка отмены заказа</h1>
    <p>
        К сожалению, произошла ошибка отмены заказа. Пожалуйста, свяжитесь с нашей службой поддержки.
    </p>
</div>

WebApplication1/Views/Cabinet/ReturnToBasket.cshtml
@model WebApplication1.Models.ViewModels.OrderViewModel
@using (Html.BeginForm("ReturnToBasket", "Cabinet", FormMethod.Post))
{
    <div class="content_page syst">
        <h1>Изменение отправленного заказа  @Model.OrderId</h1>
        @Html.HiddenFor(model => model.OrderId)
        @Html.AntiForgeryToken()
        <p>
            Если вы нажмёте сейчас кнопку "Вернуть в корзину", этот заказ будет отменён, а товары из него вернутся в вашу корзину. <br />
            Вы сможете откорректировать количество, а также изменить набор товаров и условия доставки.
        </p>

        <input type="submit" value="Вернуть в корзину" />
        <p>
            @Html.ActionLink("Назад к списку заказов", "OrderList")
        </p>
    </div>
}

WebApplication1/Views/Cabinet/SorryNotPayedYet.cshtml
<div class="content_page syst">
    <h1>По нашим данным, заказ пока не оплачен</h1>
    <p>
       По нашим данным заказ пока не оплачен. Если вы его уже оплатили, пожалуйста, свяжитесь с нашей службой поддержки.
       Приносим извинения за причиненные неудобства.
    </p>
    <p>Интернет-магазин "Индустрия Красоты"</p>
    <p><a href="@Url.Action("OrderList","Cabinet")">Вернуться к списку заказов</a></p>
</div>

WebApplication1/Views/Cabinet/YouCantPayCODOnline.cshtml
<div class="content_page syst">
    <h1>Для заказа выбран тип оплаты "при получении"</h1>
    <p>
        Заказы с типом оплаты "Наложенный платёж" нельзя оплатить картой на сайте.
    </p>
    <p>Интернет-магазин "Индустрия Красоты"</p>
</div>