WebApplication1/Models/ViewModels/SaleActionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication1.Models.ViewModels
{
    public class SaleActionViewModel
    {
        public string PublicityJournalId { get; set; }
        public int OrderNumber { get; set; }
        [Display(Name = "Заголовок")]
        [Required(ErrorMessage = "Пожалуйста, введите заголовок")]
        public string Title { get; set; }
        [Display(Name = "Краткое описание")]
        [Required(ErrorMessage = "Пожалуйста, введите краткое описание")]
        [DataType(DataType.MultilineText)]
        public string ShortDescription { get; set; }
        [Display(Name = "Описание")]
        [Required(ErrorMessage = "Пожалуйста, введите подробное описание акции")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        [Display(Name = "Ключевые слова")]
        public string Meta { get; set; }
        [Display(Name = "url-адрес")]
        public string UrlSlug { get; set; }
        [Display(Name = "Опубликовано?")]
        public bool Published { get; set; }
        [Display(Name = "Дата публикации")]
        public DateTime PostedOn
        { get; set; }
        [Display(Name = "Дата начала")]
        public DateTime DateBegin
        { get; set; }
        [Display(Name = "Дата окончания")]
        public DateTime DateEnd
        { get; set; }
        public string LongMainImage { get; set; }
        public string MedMainImage { get; set; }
        public string ShortMainImage { get; set; }
        public string LinkToCatalog { get; set; }

        public List<InventTableModel> PublicityItems { get; set; }
    }
}

WebApplication1/Controllers/SaleActionController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Classes;
using WebApplication1.Models.ViewModels;

namespace WebApplication1.Controllers
{
    public class SaleActionController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
            var model = new List<SaleActionViewModel>();
            try
            {
                var strUrl = DataService.GetUrl(Request);
                model = DataService.GetActionsCatalog4HomePage(strUrl, 0); //вытаскиваем вообще все акции
                ViewBag.Title = "Рекламные акции и специальные предложения";
            }
            catch
            {
                model = new List<SaleActionViewModel>();
            }
            return View(model);
        }

        public ActionResult Details(string Id)
        {
            //id здесь slug на самом деле, чтобы было красивенько
            var model = new SaleActionViewModel();
            try
            {
                string userId;

                if (Request.IsAuthenticated)
                    userId = User.Identity.GetUserId();
                else
                    userId = Request.AnonymousID;


                var strUrl = DataService.GetUrl(Request);
                model = DataService.GetSaleActionInfoBySlug(Id, strUrl);

                var selectedItems = new List<string>();

                selectedItems = DataService.GetPublicityItemsList(model.PublicityJournalId);

                model.PublicityItems = DataService.GetCatalogByItemList(selectedItems, true, strUrl, selectedItems.Count, true, userId, 0, true);

                ViewBag.Title = model.Title;

                ViewBag.Description = "Интернет-магазин профессиональной косметики Индустрия красоты. ";

                if (!string.IsNullOrWhiteSpace(model.ShortDescription))
                    ViewBag.Description = model.ShortDescription;

                ViewBag.Keywords = "Интернет-магазин Индустрия красоты. Профессиональная косметика. Интернет-магазин профессиональной косметики, купить профессиональную косметику в Ростове, купить профессиональную косметику, krasivo.pro, красиво.про, интернет-магазин Индустрия красоты Ростов, красиво про, купить в Ростове-на-Дону, купить в Ростове, ";

                if (!string.IsNullOrWhiteSpace(model.Meta))
                    ViewBag.Keywords += model.Meta;
            }
            catch
            {
                RedirectToAction("Index");
            }

            return View(model);
        }
    }
}

WebApplication1/Views/SaleAction/Details.cshtml
@model WebApplication1.Models.ViewModels.SaleActionViewModel
<main class="content">
    <div class="wrapper">

        <div class="content_page">
                @*<h1>@Html.DisplayFor(m => Model.Title)</h1>*@

                <p style="text-align:center;"><img src="@Model.LongMainImage" alt="@Model.Title" style="max-width: 100%" /></p>

                <p>Предложение действует до @Model.DateEnd.ToShortDateString()!</p>

                @*@Html.Raw(Model.Description)*@

                <div class="share_block">
                    <script src="https://yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>
                    <script src="https://yastatic.net/share2/share.js" async="async"></script>
                    <div class="ya-share2" data-services="vkontakte,facebook,odnoklassniki,gplus,twitter"></div>
                </div>

        </div>

        @if (Model.PublicityItems.Count > 0)
        {
            <div class="products bottom_list">
                <h3>Товары, участвующие в акции</h3>
                <div class="products_list">
                    @Html.Partial("ItemsPartial", Model.PublicityItems)
                </div>
            </div>
        }
    </div>
</main><!-- .content -->

WebApplication1/Views/SaleAction/Index.cshtml
@model IEnumerable<WebApplication1.Models.ViewModels.SaleActionViewModel>

<main class="content">
    <div class="wrapper">
        @*<div class="breadcrumbs">
                <ul>
                    <li><a href="#"><i class="fa fa-home" aria-hidden="true"></i></a><i class="fa fa-angle-right" aria-hidden="true"></i></li>
                    <li><span>Бренды</span></li>
                </ul>
            </div>*@

        <div class="content_page">
            <div class="page_block full">
                <div class="blog_block">
                    <h1>Акции</h1>
                    <div class="cl"></div>
                    @{ if (Model.Any())
                        {
                            <div class="blog_list">
                                @{foreach (var item in Model)
                                    {
                                        <text>
                                            <div class="item">
                                                <a href="@Url.Action("Details", "SaleAction", new { Id = item.UrlSlug })" class="photo" ><img src="@item.MedMainImage" alt="@item.Title" style="max-width: 100%"/></a>
                                                <div class="descr">
                                                    <a href="@Url.Action("Details", "SaleAction", new { Id = item.UrlSlug })" class="title">@item.Title</a>
                                                    <div class="anons">
                                                        <p>Предложение действует с @item.DateBegin.ToShortDateString() до @item.DateEnd.ToShortDateString()</p>
                                                        <p>@item.ShortDescription</p>                                                        
                                                    </div>
                                                </div>
                                            </div>
                                        </text>
                                    }
                                }
                            </div>
                                    }
                                    else
                                    {
                                        <text>
                                            <div class="cl"></div>
                                        </text>
                                        @Html.Raw("<p>Извините, раздел в разработке</p>");
                                    }
                    }
                </div>
             </div>
            @*<p>SEO текст</p>*@
            <div class="share_block">
                <script src="https://yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>
                <script src="https://yastatic.net/share2/share.js" async="async"></script>
                <div class="ya-share2" data-services="vkontakte,facebook,odnoklassniki,gplus,twitter"></div>
            </div>

        </div>
     </div>
</main>


@*<div class="blog_block">
    <h3>Акции</h3>
    <div class="cl"></div>
    <div class="blog_list">
        <div class="item">
            <a href="#" class="photo"><img src="pic/pic-1.jpg" alt="" /></a>
            <div class="descr">
                <a href="#" class="title">Заголовок поста</a>
                <div class="anons">
                    <p>Update: In the above video, Blac opens up about her burn incident, how she used makeup as a shield, and why she encourages viewers to love themselves...</p>
                </div>
            </div>
        </div>
        <div class="item">
            <a href="#" class="photo"><img src="pic/pic-2.jpg" alt="" /></a>
            <div class="descr">
                <a href="#" class="title">Заголовок поста</a>
                <div class="anons">
                    <p>Update: In the above video, Blac opens up about her burn incident, how she used makeup as a shield, and why she encourages viewers to love themselves...</p>
                </div>
            </div>
        </div>
    </div>
    <div class="item_video">
        <div class="player">
            <iframe width="770" height="433" src="https://www.youtube.com/embed/lJVZM-sqxN8" frameborder="0" allowfullscreen></iframe>
        </div>
        <a href="#" class="title">Заголовок поста блога с видео записью от Youtube</a>
    </div>
    <div class="cl"></div>
</div>*@